version: 0.2

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: .
post_build:
   commands:
     - aws cloudfront create-invalidation --distribution-id=E3V5SYI6SJ4XXZ --paths '/*'
